# Generated by Django 2.2.3 on 2021-04-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('URL', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
            ],
            options={
                'db_table': 'details',
                'managed': True,
            },
        ),
    ]
