# Generated by Django 2.2.3 on 2021-04-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='URL',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='details',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
